FROM node:alpine AS build

WORKDIR /app

COPY package.json /app

RUN yarn install && yarn cache clean

COPY . /app

RUN yarn run build

# production environment
FROM nginx:alpine
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx/nginx_config /etc/nginx/nginx.conf
COPY orig-czndk/czndk /var/www/orig-czndk/czndk
COPY orig-czndk/cs /var/www/orig-czndk/cs
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
EXPOSE 442
CMD ["nginx", "-g", "daemon off;"]